# Emit klengine_test.cpp — checks KLEngine (C++) against the validated Python
# interpreter (ground truth) for BOTH the Unicode and Classic tables.
import os
from keylayout_interp import KeyLayout, K

def esc(s):
    o = []
    for ch in s:
        cp = ord(ch)
        if ch == '"':  o.append('\\"')
        elif ch == '\\': o.append('\\\\')
        elif 0x20 <= cp < 0x7f: o.append(ch)
        else: o.append('\\u%04x' % cp)
    return 'u"' + ''.join(o) + '"'

here = os.path.dirname(os.path.abspath(__file__))
kld = os.path.join(here, '..', '..', 'macos', 'src', 'keylayouts')
uni = KeyLayout(os.path.join(kld, 'Bangla Unicode.keylayout'))
cls = KeyLayout(os.path.join(kld, 'Bangla Classic.keylayout'))
phon = KeyLayout(os.path.join(kld, 'Bangla Phonetic.keylayout'))

# Phonetic specs come from the SHIPPED corpus (macos/src/phonetic/tests.tsv) so the
# build-time self-test always checks the same cases the macOS side does. Typed text
# -> key-spec: an uppercase letter / shifted symbol becomes "^<unshifted key>".
SHIFTED = {'~': '`', '!': '1', '@': '2', '#': '3', '$': '4', '%': '5', '^': '6', '&': '7',
           '*': '8', '(': '9', ')': '0', '_': '-', '+': '=', '{': '[', '}': ']', '|': '\\',
           ':': ';', '"': "'", '<': ',', '>': '.', '?': '/'}

def spec_of(typed):
    toks = []
    for ch in typed:
        if ch.isalpha() and ch.isupper(): toks.append('^' + ch.lower())
        elif ch in SHIFTED:               toks.append('^' + SHIFTED[ch])
        else:                             toks.append(ch)
    return ' '.join(toks)

# NOTE: entries containing a key the LAYOUT doesn't own (Space) are skipped here.
# The spec notation uses space as its token separator, and more importantly "Space"
# is not a layout key at all: the SHELL flushes the engine and passes the character
# through. This harness only drives KLEngine, so it cannot model that — baking such a
# case in would assert a space-less string and pass vacuously. Those sentence cases
# ARE covered, with the real pass-through behaviour, by phonetic_check.py (which
# compares the full 123-case corpus against the shipped tests.tsv expectations).
PHON = []
for line in open(os.path.join(here, '..', '..', 'macos', 'src', 'phonetic', 'tests.tsv'),
                 encoding='utf-8'):
    line = line.rstrip('\n')
    if line and not line.startswith('#'):
        typed = line.split('\t')[0]
        if ' ' in typed: continue
        PHON.append(spec_of(typed))

# Unicode specs — note the corrected vowel behaviour (matches macOS):
#   f -> া,  ^f -> অ,  ^f f -> আ,  isolated matras stay matras.
UNI = ['c j', 'd j', 'c j f', '^c j', 'd j g ^n', 'i c y g ^y', '^h f n ^a b',
       'j m ^a', 'd ^r z', 'h f ^q ^v f', 'h ^v', 'j f', 'f', '^f', '^f f',
       '^f f m d', 'd', 'c', 'x', '^f d']
CLS = ['j', 'i', '^h', 'c j', 'j m ^a', '^h f n ^a b', 'h f ^q ^v f', 'd j g ^n',
       'i c y g ^y', 'f', '^f', 'h ^v']

def cases(layout, specs):
    return [(s, layout.type_keys(K(s))) for s in specs]

uni_cases = cases(uni, UNI)
cls_cases = cases(cls, CLS)
phon_cases = cases(phon, PHON)

L = []
L.append('// AUTO-GENERATED by gen_klengine_test.py — expected = the validated')
L.append('// keylayout interpreter (ground truth from the macOS .keylayout files).')
L.append('#include "klengine.h"')
L.append('#include "unicode_table.h"')
L.append('#include "classic_table.h"')
L.append('#include "phonetic_table.h"')
L.append('#include <cstdio>')
L.append('#include <string>')
L.append('#include <vector>')
L.append('using bangla::KLEngine;')
L.append('static unsigned scanOf(char c){switch(c){'
         "case '`':return 0x29;case '1':return 0x02;case '2':return 0x03;case '3':return 0x04;"
         "case '4':return 0x05;case '5':return 0x06;case '6':return 0x07;case '7':return 0x08;"
         "case '8':return 0x09;case '9':return 0x0A;case '0':return 0x0B;case '-':return 0x0C;case '=':return 0x0D;"
         "case 'q':return 0x10;case 'w':return 0x11;case 'e':return 0x12;case 'r':return 0x13;case 't':return 0x14;"
         "case 'y':return 0x15;case 'u':return 0x16;case 'i':return 0x17;case 'o':return 0x18;case 'p':return 0x19;"
         "case '[':return 0x1A;case ']':return 0x1B;case '\\\\':return 0x2B;"
         "case 'a':return 0x1E;case 's':return 0x1F;case 'd':return 0x20;case 'f':return 0x21;case 'g':return 0x22;"
         "case 'h':return 0x23;case 'j':return 0x24;case 'k':return 0x25;case 'l':return 0x26;case ';':return 0x27;case '\\'':return 0x28;"
         "case 'z':return 0x2C;case 'x':return 0x2D;case 'c':return 0x2E;case 'v':return 0x2F;case 'b':return 0x30;"
         "case 'n':return 0x31;case 'm':return 0x32;case ',':return 0x33;case '.':return 0x34;case '/':return 0x35;"
         'default:return 0;}}')
L.append('static std::u16string typeKeys(const bangla::Table* tb,const std::string& spec){KLEngine e(tb);std::u16string out;std::string tok;'
         'auto play=[&](const std::string& t){if(t.empty())return;bool sh=t[0]==\'^\';char k=sh?t[1]:t[0];out+=e.process(scanOf(k),sh);};'
         'for(char ch:spec){if(ch==\' \'){play(tok);tok.clear();}else tok+=ch;}play(tok);out+=e.flush();return out;}')
L.append('struct Case{const char* spec;const char16_t* expected;};')
L.append('static int run(const char* name,const bangla::Table* tb,const std::vector<Case>& cs){int pass=0;')
L.append('  std::printf("== %s ==\\n",name);')
L.append('  for(auto&c:cs){std::u16string g=typeKeys(tb,c.spec);std::u16string e=c.expected;bool ok=(g==e);pass+=ok;')
L.append('    std::printf("[%s] %-14s\\n", ok?"PASS":"FAIL", c.spec);')
L.append('    if(!ok){std::printf("      got "); for(char16_t x:g) std::printf("U+%04X ",(unsigned)x);')
L.append('            std::printf("\\n      exp "); for(char16_t x:e) std::printf("U+%04X ",(unsigned)x); std::printf("\\n");}}')
L.append('  std::printf("%d/%d\\n\\n",pass,(int)cs.size());return pass==(int)cs.size();}')
L.append('int main(){')
L.append('  std::vector<Case> uni = {')
for s, out in uni_cases:
    L.append('    {%-18s %s},' % ('"' + s + '",', esc(out)))
L.append('  };')
L.append('  std::vector<Case> cls = {')
for s, out in cls_cases:
    L.append('    {%-18s %s},' % ('"' + s + '",', esc(out)))
L.append('  };')
L.append('  std::vector<Case> phon = {')
for s, out in phon_cases:
    L.append('    {%-34s %s},' % ('"' + s + '",', esc(out)))
L.append('  };')
L.append('  bool a = run("Bangla Unicode", &bangla::unicode_table::TABLE, uni);')
L.append('  bool b = run("Bangla Classic", &bangla::classic_table::TABLE, cls);')
L.append('  bool c = run("Bangla Phonetic", &bangla::phonetic_table::TABLE, phon);')
L.append('  return (a&&b&&c)?0:1;')
L.append('}')

dst = os.path.join(here, 'klengine_test.cpp')
with open(dst, 'w', encoding='utf-8') as fh:
    fh.write('\n'.join(L) + '\n')
print('wrote', dst, 'uni=%d cls=%d' % (len(uni_cases), len(cls_cases)))
