# Generate unicode_table.h and classic_table.h — the macOS .keylayout deadkey
# FSMs as C++ tables for KLEngine (klengine.h). Run after any .keylayout change:
#   python gen_tables.py
import os
from keylayout_interp import KeyLayout

# macOS virtual keycode -> Windows Set-1 scan code (US-QWERTY positions)
KC2SCAN = {
 0:0x1E,1:0x1F,2:0x20,3:0x21,4:0x23,5:0x22,6:0x2C,7:0x2D,8:0x2E,9:0x2F,11:0x30,
 12:0x10,13:0x11,14:0x12,15:0x13,16:0x15,17:0x14,18:0x02,19:0x03,20:0x04,21:0x05,
 22:0x07,23:0x06,24:0x0D,25:0x0A,26:0x08,27:0x0C,28:0x09,29:0x0B,30:0x1B,31:0x18,
 32:0x16,33:0x1A,34:0x17,35:0x19,37:0x26,38:0x24,39:0x28,40:0x25,41:0x27,42:0x2B,
 43:0x33,44:0x35,45:0x31,46:0x32,47:0x34,50:0x29,
}

def cpp_u16(s):
    out = []
    for ch in s:
        cp = ord(ch)
        if ch == '"':  out.append('\\"')
        elif ch == '\\': out.append('\\\\')
        elif 0x20 <= cp < 0x7F: out.append(ch)
        else: out.append('\\u%04x' % cp)
    return 'u"' + ''.join(out) + '"'

def gen(src_keylayout, out_path, ns, title):
    L = KeyLayout(src_keylayout)
    states = {'none': 0}
    strings = {'': 0}
    def sid(s):
        if s not in states: states[s] = len(states)
        return states[s]
    def oid(s):
        s = s or ''
        if s not in strings: strings[s] = len(strings)
        return strings[s]

    actions = {}
    def action_rules(name):
        if name in actions: return name
        rules = []
        for st, (out, nxt) in L.actions.get(name, {}).items():
            rules.append((sid(st), oid(out), sid(nxt) if nxt else 0))
        actions[name] = rules
        return name
    def synth_output(out):
        key = '#o:%d' % oid(out)
        if key not in actions: actions[key] = [(0, oid(out), 0)]
        return key

    keymap = {0: {}, 1: {}}
    for shift, idx in ((0, L.base_idx), (1, L.shift_idx)):
        for kc, (kind, val) in L.keymaps.get(idx, {}).items():
            scan = KC2SCAN.get(kc)
            if scan is None: continue
            keymap[shift][scan] = synth_output(val) if kind == 'output' else action_rules(val)

    term = {sid(st): oid(out) for st, out in L.terminators.items()}

    anames = list(actions.keys())
    aid = {n: i for i, n in enumerate(anames)}
    flat, aspan = [], []
    for n in anames:
        aspan.append((len(flat), len(actions[n])))
        flat.extend(actions[n])

    nstates = len(states)
    inv_strings = [None] * len(strings)
    for s, i in strings.items(): inv_strings[i] = s
    termarr = [0] * nstates
    for st, o in term.items(): termarr[st] = o

    o = []
    o.append('// AUTO-GENERATED by gen_tables.py from macOS "%s" — do not edit.' % title)
    o.append('// %s deadkey FSM for KLEngine, keyed by Windows scan code.' % title)
    guard = 'BANGLA_%s_TABLE_H' % ns.upper()
    o.append('#ifndef %s' % guard)
    o.append('#define %s' % guard)
    o.append('#include "klengine.h"')
    o.append('namespace bangla { namespace %s {' % ns)
    o.append('static const int NSTATES = %d;' % nstates)
    o.append('static const char16_t* const STRINGS[] = {')
    o.append('  ' + ', '.join(cpp_u16(s) for s in inv_strings))
    o.append('};')
    o.append('static const Rule RULES[] = {')
    line = '  '
    for (st, ou, nx) in flat:
        line += '{%d,%d,%d},' % (st, ou, nx)
        if len(line) > 110: o.append(line); line = '  '
    if line.strip(): o.append(line)
    o.append('};')
    o.append('static const Span ACTIONS[] = {')
    line = '  '
    for (off, cnt) in aspan:
        line += '{%d,%d},' % (off, cnt)
        if len(line) > 110: o.append(line); line = '  '
    if line.strip(): o.append(line)
    o.append('};')
    o.append('static const short TERM[] = {')
    o.append('  ' + ','.join(str(x) for x in termarr))
    o.append('};')
    o.append('static const short KEYMAP[2][256] = {')
    for shift in (0, 1):
        row = [-1] * 256
        for scan, name in keymap[shift].items():
            row[scan] = aid[name]
        o.append('  { ' + ','.join(str(x) for x in row) + ' },')
    o.append('};')
    o.append('static const Table TABLE = { STRINGS, RULES, ACTIONS, TERM, KEYMAP };')
    o.append('}} // namespace')
    o.append('#endif')
    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(o) + '\n')
    print('wrote %s  (states=%d strings=%d actions=%d rules=%d)' %
          (os.path.basename(out_path), nstates, len(inv_strings), len(anames), len(flat)))

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    kld = os.path.join(here, '..', '..', 'macos', 'src', 'keylayouts')
    gen(os.path.join(kld, 'Bangla Unicode.keylayout'),
        os.path.join(here, 'unicode_table.h'), 'unicode_table', 'Bangla Unicode')
    gen(os.path.join(kld, 'Bangla Classic.keylayout'),
        os.path.join(here, 'classic_table.h'), 'classic_table', 'Bangla Classic')
    gen(os.path.join(kld, 'Bangla Phonetic.keylayout'),
        os.path.join(here, 'phonetic_table.h'), 'phonetic_table', 'Bangla Phonetic')

if __name__ == '__main__':
    main()
